# Generated by Django 5.2.3 on 2025-06-22 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EmailAgentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_reply_enabled', models.BooleanField(default=False)),
                ('auto_reply_message', models.TextField(blank=True, null=True)),
                ('auto_reply_filter', models.CharField(blank=True, max_length=255, null=True)),
                ('default_tone', models.CharField(default='neutral', max_length=50)),
                ('recipient_tones', models.JSONField(blank=True, default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_agent_settings', to='authentication.googleaccount')),
            ],
        ),
        migrations.CreateModel(
            name='IncomingEmails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('is_read', models.BooleanField(default=False)),
                ('should_reply', models.BooleanField(default=False)),
                ('is_replied', models.BooleanField(default=False)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_address', to='authentication.googleaccount')),
            ],
        ),
        migrations.CreateModel(
            name='OutgoingEmails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('pending_review', 'Pending Review'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('review_timestamp', models.DateTimeField(blank=True, null=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_emails', to='authentication.googleaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_email', to='authentication.googleaccount')),
                ('recipients', models.ManyToManyField(related_name='emails_received', to='agentsworkflow.recipient')),
            ],
        ),
    ]
