# Generated by Django 5.2.3 on 2025-06-28 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentsworkflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('emailaddress', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='outgoingemails',
            name='recipients',
        ),
        migrations.RemoveField(
            model_name='outgoingemails',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='outgoingemails',
            name='user',
        ),
        migrations.RemoveField(
            model_name='incomingemails',
            name='sender_email',
        ),
        migrations.CreateModel(
            name='OutgoingMails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('email_to_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='agentsworkflow.incomingemails')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_emails', to='agentsworkflow.users')),
            ],
        ),
        migrations.AlterField(
            model_name='incomingemails',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_emails', to='agentsworkflow.users'),
        ),
        migrations.DeleteModel(
            name='EmailAgentSettings',
        ),
        migrations.DeleteModel(
            name='Recipient',
        ),
        migrations.DeleteModel(
            name='OutgoingEmails',
        ),
    ]
