# Generated by Django 5.2.3 on 2025-06-29 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentsworkflow', '0003_remove_incomingemails_user_incomingemails_reciver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingemails',
            name='is_deleted_by_recipient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incomingemails',
            name='is_deleted_by_sender',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incomingemails',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agentsworkflow.incomingemails'),
        ),
        migrations.AlterField(
            model_name='incomingemails',
            name='reciver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_emails', to='agentsworkflow.users'),
        ),
        migrations.AlterField(
            model_name='incomingemails',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_emails', to='agentsworkflow.users'),
        ),
        migrations.DeleteModel(
            name='OutgoingMails',
        ),
    ]
