# Generated by Django 5.2.3 on 2025-07-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentsworkflow', '0004_incomingemails_is_deleted_by_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingemails',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
