# Generated by Django 5.2.3 on 2025-07-03 14:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentsworkflow', '0005_incomingemails_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingemails',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
