# Generated by Django 5.2.3 on 2025-07-04 08:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentsworkflow', '0006_incomingemails_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingemails',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
