# Generated by Django 5.2.3 on 2025-07-07 10:07

import datetime
import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentsworkflow', '0007_alter_incomingemails_uuid'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='incomingemails',
            name='reply',
        ),
        migrations.AddField(
            model_name='incomingemails',
            name='headers',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='incomingemails',
            name='in_reply_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incomingemails',
            name='internal_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 7, 10, 7, 57, 578419, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incomingemails',
            name='label_ids',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='incomingemails',
            name='message_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='incomingemails',
            name='snippet',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='incomingemails',
            name='thread_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='incomingemails',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='GmailSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_id', models.CharField(blank=True, max_length=255, null=True)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='agentsworkflow.user')),
            ],
        ),
        migrations.AlterField(
            model_name='incomingemails',
            name='reciver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_emails', to='agentsworkflow.user'),
        ),
        migrations.AlterField(
            model_name='incomingemails',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_emails', to='agentsworkflow.user'),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
