# Generated by Django 5.2.3 on 2025-07-07 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentsworkflow', '0009_alter_gmailsyncstate_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GmailContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='incomingemails',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_emails', to='agentsworkflow.gmailcontact'),
        ),
    ]
