# Generated by Django 5.2.3 on 2025-07-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentsworkflow', '0010_gmailcontact_alter_incomingemails_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingemails',
            name='is_outgoing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incomingemails',
            name='is_reply_generated_by_agent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incomingemails',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incomingemails',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
