# Generated by Django 5.2.4 on 2025-07-21 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentsworkflow', '0011_incomingemails_is_outgoing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingemails',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incomingemails',
            name='headers',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='incomingemails',
            name='label_ids',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
