# Generated by Django 5.2.4 on 2025-07-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentsworkflow', '0012_alter_incomingemails_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingemails',
            name='category',
            field=models.CharField(blank=True, default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
