# Generated by Django 5.2.3 on 2025-07-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_googleaccount_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleaccount',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
